### ISSUE TITLE
Website updates Q1

### ISSUE THREAD

**Issue by burningtree** [web3privacy/core#17]
# Tasks

- [ ] web3privacy/web#1
- [x] web3privacy/web#2
- [ ] web3privacy/web#3
- [ ] web3privacy/web#4
- [ ] web3privacy/web#8
