### ISSUE TITLE
Membership v1

### ISSUE THREAD

**Issue by burningtree** [web3privacy/core#21]
For orgs & individuals

https://docs.web3privacy.info/membership

## Tasks

- [ ] Specification of all benefits (@EclecticSamurai) 
- [ ] Consultation of benefits from legal view with Simona (@burningtree)
- [ ] ask community about benefits (@Msiusko)
- [ ] Starting prices (for orgs/individuals)
- [ ] Website integration (@burningtree)
  - [ ] Graphics @coinmandeer 
  - [ ] Promo/Signup page
  - [ ] List of members
