### ISSUE TITLE
Uniform crypto addresses for donations

### ISSUE THREAD

**Issue by burningtree** [web3privacy/core#32]
# Networks

## EVM (ETH + ERC20 tokens)
* [x] ETH Mainnet -- [Multisig](https://docs.web3privacy.info/core-team/multisig)
* [x] Arbitrum -- [Multisig](https://docs.web3privacy.info/core-team/multisig)
* [ ] Optimism
* [ ] Starknet
* [ ] Base
* [ ] Polygon
* [ ] Gnosis Chain

## Other networks

* [ ] Bitcoin (BTC)
* [ ] Bitcoin (LN-BTC) ([The Lightning Address](https://lightningaddress.com/)?)
* [ ] Monero (XMR) ([Rino](https://www.rino.io/) multisig?)
* [ ] Zcash (ZEC)

# Subtasks
## Fixing `web3privacy` repo

There is old addresses in [`@web3privacy/web3privacy`](https://github.com/web3privacy/web3privacy) repository. They should be replaced with new multi-sig addresses.

For example:

* https://github.com/web3privacy/web3privacy/blob/cb3bc98898e586d073037dbb99ecacc26179fadb/README.md?plain=1#L817-L824
* https://github.com/web3privacy/web3privacy/blob/cb3bc98898e586d073037dbb99ecacc26179fadb/Web3privacynowplatform/Readme.md?plain=1#L131-L137
