### ISSUE TITLE
Research Systematization

### ISSUE THREAD

**Issue by burningtree** [web3privacy/core#37]
Tasks regarding the systematization & automation of our Research department web3privacy/projects#2

## Tasks

- [x] Start using the [W3PN Research](https://github.com/orgs/web3privacy/projects/11) GitHub project for tracking research states
- [ ] Finish Research documentation web3privacy/docs#4
- [ ] Update "Research" page on website web3privacy/web#4

## Related tasks

- #15
